## Numpy Array Creation & Attributes Illustration
* Create numpy arrays 
* Review the attributes of created numpy array
* Reference: https://numpy.org/doc/stable/user/quickstart.html

In [1]:
# Check the latest package version of numpy
!pip show numpy

Name: numpy
Version: 1.21.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\user\anaconda3\lib\site-packages
Requires: 
Required-by: astropy, bkcharts, bokeh, Bottleneck, h5py, imagecodecs, imageio, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tifffile


In [2]:
# import numpy library
import numpy as np

In [7]:
# Use arange() to create random 15 value array (1-d).
print(np.arange(15))

# use reshape(m,n) to create mxn matrix
print(np.arange(15).reshape(3,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
# Create a numpy array
a = np.arange(15).reshape(3, 5)

In [10]:
# Check attributes
# a.ndim 
# a.shape
# a.size
# a.dtype
# a.itemsize
# a.data

print("a.ndim: ", a.ndim)
print("a.shape: ", a.shape)
print("a.size: ", a.size)
print("a.dtype: ", a.dtype)
print("a.itemsize: ", a.itemsize)
print("a.data: ", a.data)

a.ndim:  2
a.shape:  (3, 5)
a.size:  15
a.dtype:  int32
a.itemsize:  4
a.data:  <memory at 0x000001D1D279FBA0>


In [15]:
# Create a ndarray similar to "a" using array() function
b = np.array([np.arange(0,5), 5+ np.arange(0,5), 10+ np.arange(0,5) ])
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
print("b.ndim: ", b.ndim)
print("b.shape: ", b.shape)
print("b.size: ", b.size)
print("b.dtype: ", b.dtype)
print("b.itemsize: ", b.itemsize)
print("b.data: ", b.data)

b.ndim:  2
b.shape:  (3, 5)
b.size:  15
b.dtype:  int32
b.itemsize:  4
b.data:  <memory at 0x000001D1D279FBA0>


In [16]:
# Create a complex numbers ndarray
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
print("c.ndim: ", c.ndim)
print("c.shape: ", c.shape)
print("c.size: ", c.size)
print("c.dtype: ", c.dtype)
print("c.itemsize: ", c.itemsize)
print("c.data: ", c.data)

c.ndim:  2
c.shape:  (2, 2)
c.size:  4
c.dtype:  complex128
c.itemsize:  16
c.data:  <memory at 0x000001D1D27D2380>


In [4]:
# Create a matrix of zeros using zeros()
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Create an identity matrix using ones()
# make sure to use data type (dtype = int16)
np.ones((4,4), dtype = np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [10]:
# Create an empty matrix using empty()
# creates a matrix of infinitesimal small values
np.empty((4,4))

array([[7.73730967e-312, 4.29837112e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11256817e-306, 1.16095484e-028, 1.50758157e+161,
        9.32219551e+218],
       [2.17436711e+243, 1.69375696e+190, 2.03537408e-110,
        3.65093134e+233],
       [4.03680807e-144, 2.91237123e+257, 4.71294503e+257,
        2.60094651e-306]])

In [16]:
# Use linspace() to create values between two numbers
# create 10 values between 0 and 1
print(np.linspace(0,1,10))

# create 9 values between 0 and 10
print(np.linspace(0,10,9))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [18]:
# Create multi-dimensional arrays
print("1-d array")
print(np.arange(6)) # 1-d array
print("2-d array")
print(np.arange(12).reshape(4, 3) ) #2-d array
print("3-d array")
print(np.arange(24).reshape(2, 3, 4)) #3-d array
print("4-d array")
print(np.arange(24).reshape(2, 3, 2, 2)) #4-d array

1-d array
[0 1 2 3 4 5]
2-d array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3-d array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
4-d array
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
