# Basic Operations
* Arithmetic operators on arrays apply elementwise. 
* A new array is created and filled with the result.

In [1]:
import numpy as np

In [3]:
# create a 1-d ndarray named "a"
a = np.array([20, 30, 40, 50])

# create a 1-d ndarray named "b"
b = np.arange(4)

print("a :", a)
print("b :", b)

a : [20 30 40 50]
b : [0 1 2 3]


In [5]:
# addition operations
print("a+b : ", a+b)
print("a+b+b : ", a+b+b)

a+b :  [20 31 42 53]
a+b+b :  [20 32 44 56]


In [6]:
# subtraction operations
c = a - b
print("c: ", c)

print("b-a: ", b-a)

c:  [20 29 38 47]
b-a:  [-20 -29 -38 -47]


In [7]:
# power operations
b**2

array([0, 1, 4, 9], dtype=int32)

In [8]:
# multiplication operations
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [9]:
# boolean operations
a < 35

array([ True,  True, False, False])

## Unary operations
* Numpy unary operations are performed as methods of Numpy Objects

In [21]:
x = np.array((1,2,3,4,5), dtype = int)
print("x : ", x)
print("sum of x : ", x.sum())
print("min of x : ", x.min() )
print("max of x : ", x.max() )
print("mean of x : ", x.mean() )
#print("median of x : ", x.median() )
#print("sd of x : ", x.sd() )

x :  [1 2 3 4 5]
sum of x :  15
min of x :  1
max of x :  5
mean of x :  3.0


## Matrix Operations
* The product operator `*` operates elementwise in NumPy arrays. 
* The matrix product performed using the @ operator (in python >=3.5) or the *`dot`* function or method

In [18]:
# Create two matrices A and B using Numpy array() function
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])

print("Matrix A: \n", A)
print("Matrix B: \n", B)

Matrix A: 
 [[1 1]
 [0 1]]
Matrix B: 
 [[2 0]
 [3 4]]


In [13]:
# Element-wise product
A * B     

array([[2, 0],
       [0, 4]])

In [14]:
# matrix product
A @ B     

array([[5, 4],
       [3, 4]])

In [15]:
# another way of achieveing matrix product
A.dot(B)  

array([[5, 4],
       [3, 4]])

In [19]:
# operators such as *= and += act as modifying existing arrays instead of creating new arrays

print( "A : \n", A)

A *= 3

print( "A *= 3 : \n ", A)

A : 
 [[1 1]
 [0 1]]
A *= 3 : 
  [[3 3]
 [0 3]]


In [20]:
C = np.ones((2,2), dtype=int)
print("C : \n", C)
A += C
print("A : \n", A)

C : 
 [[1 1]
 [1 1]]
A : 
 [[4 4]
 [1 4]]


## Universal functions
* np.add
* np.exp
* np.log
* np.sqrt
* np.square
* and many more

In [25]:
print("A : \n", A)
print("B : \n", B)

print("A+B : \n", np.add(A,B))


A : 
 [[4 4]
 [1 4]]
B : 
 [[2 0]
 [3 4]]
A+B : 
 [[6 4]
 [4 8]]


In [26]:
print("A : \n", A)
print("exponential of A : \n", np.exp(A))

print("Log of A : \n", np.log(A))

A : 
 [[4 4]
 [1 4]]
exponential of A : 
 [[54.59815003 54.59815003]
 [ 2.71828183 54.59815003]]
Log of A : 
 [[1.38629436 1.38629436]
 [0.         1.38629436]]


In [27]:
print("A : \n", A)
print("Square of A : \n", np.square(A))

print("Square root of A : \n", np.sqrt(A))

A : 
 [[4 4]
 [1 4]]
Square of A : 
 [[16 16]
 [ 1 16]]
Square root of A : 
 [[2. 2.]
 [1. 2.]]


## Indexing, Slicing and Iterating
* One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
* Multi-dimensional arrays

In [2]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [4]:
# extract the fourth element
a[3]

27

In [7]:
# extract all elements
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [6]:
# extract all elements from 5th to 8th positions
a[4:8]

array([ 64, 125, 216, 343], dtype=int32)

In [8]:
# from 5th element to last element in array
a[4:]

array([ 64, 125, 216, 343, 512, 729], dtype=int32)

In [9]:
# from the first element in an array upto 8th element (including 8th element)
a[:8]

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

## Multidimensional array
* Indexing, Slicing and Iterating

In [3]:
# a 3D array (two stacked 2D arrays)
c = np.array([[[  0,  1,  2],  
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
c

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [13]:
# Check the dimenstions of c ndarray
c.shape

(2, 2, 3)

In [14]:
# extract all elements
c[::]

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [5]:
# extract all elements
c[0:,:]

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [30]:
# extract first elements (2x3 matrix) on first axis
c[0:1,:]

array([[[ 0,  1,  2],
        [10, 12, 13]]])

In [4]:
# extract second elements (2x3 matrix) on first axis
c[1:,:]

array([[[100, 101, 102],
        [110, 112, 113]]])

In [6]:
# In both the matrices, fetch 2nd row 3rd & 2nd elements
c[:,1,[2,1]]


array([[ 13,  12],
       [113, 112]])

In [7]:
# In the 2nd matrix, fetch 2nd row 3rd & 2nd elements
c[1:,1,[2,1]]

array([[113, 112]])

## Create field names for numpy array, and index by field names

In [8]:
# Create field names n numpy array 
x = np.array([(1,2)], dtype=[('value','f4'), ('amount','c8')])

In [10]:
# Access the elements by field names in numpy array
print(x['amount'])
print(x['value'])

[2.+0.j]
[1.]


## Stacking numpy arrays
* *hstack* for horizontal stacking
* *vstack* for vertical stacking
* *c_* for column-wise stacking
* *r_* for row-wise stacking

In [12]:
# Create numpy arrays
x = np.arange(7)
y = np.square(x)
print("x : ", x)
print("y : ", y)

x :  [0 1 2 3 4 5 6]
y :  [ 0  1  4  9 16 25 36]


In [15]:
# hstack Horizontal stacking
np.hstack([x,y])

array([ 0,  1,  2,  3,  4,  5,  6,  0,  1,  4,  9, 16, 25, 36])

In [16]:
# vstack Vertical stacking
np.vstack([x,y])

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 0,  1,  4,  9, 16, 25, 36]])

In [19]:
# c_ Column-wise stacking
np.c_[x,y]

array([[ 0,  0],
       [ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [20]:
# r_ Row-wise stacking
np.r_[x,y]

array([ 0,  1,  2,  3,  4,  5,  6,  0,  1,  4,  9, 16, 25, 36])

## Duplicate numpy arrays
* Use repeat and tile methods
* repeat for duplicating elements in numpy array
* tile for a layout that creates a matrix of required shape

In [22]:
# use repeat to duplicate numpy array values
print("x : ", x)
print("duplicate x values two times : ", np.repeat(x,2))

x :  [0 1 2 3 4 5 6]
duplicate x values two times :  [0 0 1 1 2 2 3 3 4 4 5 5 6 6]


In [25]:
# use tile to duplicate numpy array in a matrix format
print("x : ", x)
print("create a duplication of x two times in two rows of matrix : \n", np.tile(x,(2,1)))

x :  [0 1 2 3 4 5 6]
create a duplication of x two times in two rows of matrix : 
 [[0 1 2 3 4 5 6]
 [0 1 2 3 4 5 6]]


## Reshape numpy arrays using reshape method

In [41]:
x = np.arange(8)
print("x : ", x)
print("Reshape x array into 2x4 matrix  : \n", np.reshape(x,(2,4)))
print("Reshape x array into 4x2 matrix : \n", x.reshape(4,2))

x :  [0 1 2 3 4 5 6 7]
Reshape x array into 2x4 matrix  : 
 [[0 1 2 3]
 [4 5 6 7]]
Reshape x array into 4x2 matrix : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [37]:
# reshape numpy arrays using Transpose using .T or .transpose()
print("x : ", x.reshape(2,4))
print("x.reshape(2,4) shape : ", x.reshape(2,4).shape)
print("x.reshape(2,4) transpose using .T : ", x.reshape(2,4).T)
print("x.reshape(2,4).T shape : ", x.reshape(2,4).T.shape)
print("x.reshape(2,4) transpose using transpose() method : ", x.reshape(2,4).transpose())
print("x.reshape(2,4).transpose(). shape : ", x.reshape(2,4).transpose().shape)


x :  [[0 1 2 3]
 [4 5 6 7]]
x shape :  (2, 4)
x transpose using .T :  [[0 4]
 [1 5]
 [2 6]
 [3 7]]
x.T shape :  (4, 2)
x transpose using transpose() method :  [[0 4]
 [1 5]
 [2 6]
 [3 7]]
x.transpose(). shape :  (4, 2)


## Logical operations

In [40]:
print("x : ", x)
print("values in x greater than 3 : ", x>3)
print("values in x greater than 3 : ",np.where(x>3))

x :  [0 1 2 3 4 5 6 7]
values in x greater than 3 :  [False False False False  True  True  True  True]
values in x greater than 3 :  (array([4, 5, 6, 7], dtype=int64),)
